export const storageKeys = {
  gameProgress: 'mental_math_trainer.game_progress.v1',
  neuroFusionProgress: 'mental_math_trainer.neuro_fusion_progress.v1',
  neuroPassCachedManifest: 'mental_math_trainer.neuro_pass_cached_manifest.v1',
  neuroPassProgress: 'mental_math_trainer.neuro_pass_progress.v1',
  neuroPassEntitlement: 'mental_math_trainer.neuro_pass_entitlement.v1',
  neuroPassEntitlementPrefix: 'mental_math_trainer.neuro_pass_entitlement',
  neuroPassClaimPlaceholder: 'mental_math_trainer.neuro_pass_claim_placeholder.v1',
  neuroPassIapRecords: 'mental_math_trainer.neuro_pass_iap_records_v1',
  neuroPassTierSkipDayPrefix: 'mental_math_trainer.neuro_pass_tier_skip_day',
  neuroPassLastSeenSeasonId: 'mental_math_trainer.neuro_pass_last_seen_season_id.v1',
  neuroPassLastAppliedSeasonState: 'mental_math_trainer.neuro_pass_last_applied_season_state.v1',
  neuroPassLastUpsellAtUtc: 'mental_math_trainer.neuro_pass_last_upsell_at_utc.v1',
  neuroPassXpGrants: 'mental_math_trainer.neuro_pass_xp_grants_v1',
  neuroPassSeenRunIds: 'mental_math_trainer.neuro_pass_seen_run_ids_v1',
  neuroPassTimeHeuristicState: 'mental_math_trainer.neuro_pass_time_heuristic_state_v1',
  neuroPassQuests: 'mental_math_trainer.neuro_pass_quests_v1',
  neuroPassQuestKeys: 'mental_math_trainer.neuro_pass_quest_keys_v1',
  neuroPassInventory: 'mental_math_trainer.neuro_pass_inventory_v1',
  appLanguage: 'mental_math_trainer.app_language.v1',
  answerEvents: 'mental_math_trainer.answer_events.v1',
  brainScores: 'mental_math_trainer.brain_scores.v1',
  themePreference: 'mental_math_trainer.theme_preference.v1',
} as const;
