import type { GameThemeDefinition } from '@features/theme/domain/entities/GameTheme';

export const DEFAULT_THEME_ID = 'focus-mode';

export const THEME_CATALOG: readonly GameThemeDefinition[] = [
  {
    id: 'focus-mode',
    name: 'Focus Mode',
    category: 'free',
    primaryColor: '#0B8F87',
    secondaryColor: '#114A7A',
    backgroundGradient: ['#E8F4FF', '#F4F8FF', '#E6FFFA'],
    accentColor: '#F97316',
    successColor: '#14B87A',
    errorColor: '#EF476F',
    surfaceColor: '#FFFFFF',
    hudStyle: 'minimal',
    animationStyle: 'subtle',
    typographyStyle: 'focus',
    soundPack: 'focus_clicks',
    particleEffectType: 'none',
    unlockRule: {
      type: 'free',
    },
    marketing: {
      emotionalFeel: 'Calm, sharp, and cognitively clean.',
      targetPersona: 'Students and professionals optimizing daily focus sessions.',
      tagline: 'Train clean. Think faster.',
      appStoreConcept:
        'Split screen: timer, streak, and a crystal-clear keypad over a mint-blue gradient.',
      instagramStoryIdea:
        'One-minute focus challenge with speed meter and no-distraction visual style.',
      beforeAfterConcept:
        'Messy brain clutter -> Focus Mode interface with speed and accuracy jump.',
      sampleAdCopy: 'Zero noise. Pure brain reps. Unlock your fastest focus in 60 seconds.',
    },
  },
  {
    id: 'minimal-zen',
    name: 'Minimal Zen',
    category: 'free',
    primaryColor: '#1A7F64',
    secondaryColor: '#2D5F73',
    backgroundGradient: ['#F8FFF9', '#ECFFF5', '#E8F8FF'],
    accentColor: '#F59E0B',
    successColor: '#16A34A',
    errorColor: '#DC2626',
    surfaceColor: '#FDFEFE',
    hudStyle: 'minimal',
    animationStyle: 'subtle',
    typographyStyle: 'zen',
    soundPack: 'glass_chimes',
    particleEffectType: 'none',
    unlockRule: {
      type: 'free',
    },
    marketing: {
      emotionalFeel: 'Breathable, mindful, and low-pressure.',
      targetPersona: 'Users who prefer slow, intentional practice and meditation-like UX.',
      tagline: 'Calm practice. Relentless progress.',
      appStoreConcept: 'Soft green-white scene with one equation centered and no visual noise.',
      instagramStoryIdea: 'Zen countdown with inhale-exhale pacing and calm answer reveal.',
      beforeAfterConcept:
        'Stressful timer visuals -> Zen layout with smoother rhythm and fewer mistakes.',
      sampleAdCopy: 'Math training without chaos. Build speed while staying calm.',
    },
  },
  {
    id: 'color-blast',
    name: 'Color Blast',
    category: 'free',
    primaryColor: '#0EA5E9',
    secondaryColor: '#F43F5E',
    backgroundGradient: ['#FDF2FF', '#E0F2FE', '#FFF7ED'],
    accentColor: '#8B5CF6',
    successColor: '#22C55E',
    errorColor: '#EF4444',
    surfaceColor: '#FFFFFF',
    hudStyle: 'minimal',
    animationStyle: 'energetic',
    typographyStyle: 'focus',
    soundPack: 'focus_clicks',
    particleEffectType: 'confetti',
    unlockRule: {
      type: 'free',
    },
    marketing: {
      emotionalFeel: 'Playful and high-energy.',
      targetPersona: 'Casual players who respond to color-rich, dopamine-friendly feedback.',
      tagline: 'Fast math. Instant hype.',
      appStoreConcept: 'Bright tri-color gradient with combo explosions and confetti bursts.',
      instagramStoryIdea: 'Combo chain clip with color splashes synced to every correct answer.',
      beforeAfterConcept: 'Plain keypad -> Color Blast combo fireworks with score multiplier.',
      sampleAdCopy: 'Turn every right answer into a mini celebration.',
    },
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    category: 'premium',
    primaryColor: '#00F5FF',
    secondaryColor: '#8B5CF6',
    backgroundGradient: ['#020617', '#0B102A', '#1B1145'],
    accentColor: '#FF2DD1',
    successColor: '#22FF9A',
    errorColor: '#FF4D6D',
    surfaceColor: '#101A3A',
    hudStyle: 'neon',
    animationStyle: 'cyber',
    typographyStyle: 'tech',
    soundPack: 'neon_pulses',
    particleEffectType: 'electric',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Futuristic intensity and elite gamer energy.',
      targetPersona: 'Competitive users who want a high-performance esports vibe.',
      tagline: 'Run your brain at neon speed.',
      appStoreConcept: 'Dark neon stage with cyan-magenta glow trails around answer cards.',
      instagramStoryIdea: 'POV challenge clip with glitch text: Can you survive Neon Sprint?',
      beforeAfterConcept: 'Free theme baseline -> Cyber Neon with glowing combo pulses.',
      sampleAdCopy: 'Your fastest calculations deserve a faster skin. Go Cyber Neon.',
    },
  },
  {
    id: 'ice-glass',
    name: 'Ice Glass',
    category: 'premium',
    primaryColor: '#67E8F9',
    secondaryColor: '#C4B5FD',
    backgroundGradient: ['#DFF7FF', '#F0F9FF', '#E8F1FF'],
    accentColor: '#38BDF8',
    successColor: '#10B981',
    errorColor: '#FB7185',
    surfaceColor: '#F8FDFF',
    hudStyle: 'glass',
    animationStyle: 'glow',
    typographyStyle: 'zen',
    soundPack: 'glass_chimes',
    particleEffectType: 'sparkles',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Premium calm with luxury clarity.',
      targetPersona: 'Design-sensitive users who like clean translucent UI.',
      tagline: 'Cold visuals. Hot brain speed.',
      appStoreConcept: 'Frosted HUD cards over crystalline gradients and subtle lens glow.',
      instagramStoryIdea: 'Slow-motion answer reveal with glass shimmer transitions.',
      beforeAfterConcept: 'Flat cards -> Frosted glass HUD with depth and light.',
      sampleAdCopy: 'A premium ice-glass look for players who want elegance with precision.',
    },
  },
  {
    id: 'cosmic-dark',
    name: 'Cosmic Dark',
    category: 'premium',
    primaryColor: '#7C3AED',
    secondaryColor: '#0EA5E9',
    backgroundGradient: ['#02030B', '#0B1024', '#1D1B4B'],
    accentColor: '#F472B6',
    successColor: '#34D399',
    errorColor: '#FB7185',
    surfaceColor: '#111633',
    hudStyle: 'neon',
    animationStyle: 'glow',
    typographyStyle: 'elite',
    soundPack: 'neon_pulses',
    particleEffectType: 'stars',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Mysterious and cinematic.',
      targetPersona: 'Night players and sci-fi fans.',
      tagline: 'Train in deep space.',
      appStoreConcept: 'Starfield background with violet-blue radial glows around score HUD.',
      instagramStoryIdea: 'Mission control style countdown into a cosmic sprint session.',
      beforeAfterConcept: 'Daylight UI -> cinematic deep-space training cockpit.',
      sampleAdCopy: 'When the world sleeps, Cosmic Dark keeps your brain sharp.',
    },
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'premium',
    primaryColor: '#FF4DD2',
    secondaryColor: '#14B8A6',
    backgroundGradient: ['#250B3B', '#512B81', '#1D4ED8'],
    accentColor: '#FDE047',
    successColor: '#4ADE80',
    errorColor: '#FB7185',
    surfaceColor: '#2F1A56',
    hudStyle: 'neon',
    animationStyle: 'energetic',
    typographyStyle: 'retro',
    soundPack: 'retro_bleeps',
    particleEffectType: 'grid',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Nostalgic, bold, and trend-forward.',
      targetPersona: 'Gen Z players who love social-media-native aesthetics.',
      tagline: 'Retro future. Real gains.',
      appStoreConcept: 'Pink-cyan horizon grid with sunset bars and pixel streak counters.',
      instagramStoryIdea: 'Neon scanline transitions with 80s synth caption overlays.',
      beforeAfterConcept: 'Neutral interface -> vaporwave grid world with kinetic overlays.',
      sampleAdCopy: 'Math practice, but make it iconic.',
    },
  },
  {
    id: 'golden-elite',
    name: 'Golden Elite',
    category: 'premium',
    primaryColor: '#D4AF37',
    secondaryColor: '#7A5E1D',
    backgroundGradient: ['#1B1204', '#2A1C08', '#3A2A0F'],
    accentColor: '#FDE68A',
    successColor: '#84CC16',
    errorColor: '#F87171',
    surfaceColor: '#2F210C',
    hudStyle: 'glass',
    animationStyle: 'glow',
    typographyStyle: 'elite',
    soundPack: 'elite_orchestra',
    particleEffectType: 'sparkles',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Prestige and achievement.',
      targetPersona: 'High-value subscribers chasing status cosmetics.',
      tagline: 'Earn the gold standard.',
      appStoreConcept: 'Black-to-gold scene with metallic HUD edges and crown badge.',
      instagramStoryIdea: 'Premium unlock reveal with shine sweep over score milestones.',
      beforeAfterConcept: 'Standard stats card -> elite metallic command dashboard.',
      sampleAdCopy: 'Not just premium. Elite.',
    },
  },
  {
    id: 'lightning-pro',
    name: 'Lightning Pro',
    category: 'premium',
    primaryColor: '#38BDF8',
    secondaryColor: '#312E81',
    backgroundGradient: ['#020617', '#0F172A', '#1E1B4B'],
    accentColor: '#FACC15',
    successColor: '#22C55E',
    errorColor: '#EF4444',
    surfaceColor: '#12203F',
    hudStyle: 'neon',
    animationStyle: 'energetic',
    typographyStyle: 'tech',
    soundPack: 'neon_pulses',
    particleEffectType: 'electric',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Speed, urgency, and momentum.',
      targetPersona: 'Players focused on reaction time and leaderboard sprints.',
      tagline: 'Answer at lightning pace.',
      appStoreConcept: 'Electric bolts behind timer with speed heat-map overlays.',
      instagramStoryIdea: '0.7s answer challenge with lightning crack transitions.',
      beforeAfterConcept: 'Normal sprint -> speed tunnel and electric feedback.',
      sampleAdCopy: 'If you think fast, look fast.',
    },
  },
  {
    id: 'brain-matrix',
    name: 'Brain Matrix',
    category: 'collab',
    primaryColor: '#22C55E',
    secondaryColor: '#14532D',
    backgroundGradient: ['#020A04', '#06210E', '#0D2F16'],
    accentColor: '#86EFAC',
    successColor: '#4ADE80',
    errorColor: '#F87171',
    surfaceColor: '#0A2311',
    hudStyle: 'neon',
    animationStyle: 'cyber',
    typographyStyle: 'matrix',
    soundPack: 'matrix_ticks',
    particleEffectType: 'grid',
    unlockRule: {
      type: 'referral',
      minReferrals: 2,
    },
    marketing: {
      emotionalFeel: 'Hacker confidence and tactical focus.',
      targetPersona: 'Referral-driven evangelists and social challengers.',
      tagline: 'Invite. Unlock. Dominate.',
      appStoreConcept: 'Green matrix rain behind equation feed with scanline HUD.',
      instagramStoryIdea: 'Referral unlock progress bar transforming into Matrix theme reveal.',
      beforeAfterConcept: 'Default UI -> coded command center aesthetic.',
      sampleAdCopy: 'Bring 2 friends. Unlock the Matrix.',
    },
  },
  {
    id: 'stock-market',
    name: 'Stock Market',
    category: 'premium',
    primaryColor: '#22C55E',
    secondaryColor: '#0F766E',
    backgroundGradient: ['#03150F', '#053025', '#0B4A3A'],
    accentColor: '#F59E0B',
    successColor: '#4ADE80',
    errorColor: '#EF4444',
    surfaceColor: '#0E2B24',
    hudStyle: 'glass',
    animationStyle: 'energetic',
    typographyStyle: 'market',
    soundPack: 'market_ticker',
    particleEffectType: 'grid',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Performance and tactical decision speed.',
      targetPersona: 'Finance enthusiasts and users who like data-dense visuals.',
      tagline: 'Trade seconds for smarter results.',
      appStoreConcept: 'Candlestick-inspired combo graph with green/red answer pulses.',
      instagramStoryIdea: 'Session score chart animated like a live trading terminal.',
      beforeAfterConcept: 'Static stats -> dynamic market dashboard visual language.',
      sampleAdCopy: 'Your mental ROI starts here.',
    },
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    category: 'limited',
    primaryColor: '#F59E0B',
    secondaryColor: '#0EA5E9',
    backgroundGradient: ['#1A1035', '#2F1D6E', '#0C4A6E'],
    accentColor: '#F43F5E',
    successColor: '#84CC16',
    errorColor: '#EF4444',
    surfaceColor: '#2C1F57',
    hudStyle: 'retro',
    animationStyle: 'energetic',
    typographyStyle: 'retro',
    soundPack: 'retro_bleeps',
    particleEffectType: 'confetti',
    unlockRule: {
      type: 'any_of',
      rules: [
        {
          type: 'premium',
        },
        {
          type: 'one_time_purchase',
          productId: 'theme_pack_arcade_retro',
        },
      ],
    },
    marketing: {
      emotionalFeel: 'Classic arcade hype and nostalgia.',
      targetPersona: 'Players who grew up with pixel art and coin-op aesthetics.',
      tagline: 'Old-school look. New-school speed.',
      appStoreConcept: 'Pixel frame UI with CRT glow and score multiplier banner.',
      instagramStoryIdea: 'Arcade combo montage with chiptune hits and scanline filter.',
      beforeAfterConcept: 'Modern UI -> retro cabinet game skin.',
      sampleAdCopy: 'Tap into arcade nostalgia while training elite reflex math.',
    },
  },
  {
    id: 'sunset-gradient',
    name: 'Sunset Gradient',
    category: 'seasonal',
    primaryColor: '#FB7185',
    secondaryColor: '#F97316',
    backgroundGradient: ['#2D0B43', '#6B21A8', '#F97316'],
    accentColor: '#FDE047',
    successColor: '#4ADE80',
    errorColor: '#F43F5E',
    surfaceColor: '#5B2575',
    hudStyle: 'glass',
    animationStyle: 'subtle',
    typographyStyle: 'elite',
    soundPack: 'glass_chimes',
    particleEffectType: 'sparkles',
    unlockRule: {
      type: 'seasonal',
      seasonId: 'summer_drop',
    },
    marketing: {
      emotionalFeel: 'Warm, aspirational, and lifestyle-driven.',
      targetPersona: 'Social sharing users who post visual progress moments.',
      tagline: 'Golden hour for your brain.',
      appStoreConcept: 'Sunset gradient sweep with evening challenge badge and glow timer.',
      instagramStoryIdea: 'Sunset countdown challenge template with score sticker.',
      beforeAfterConcept: 'Default tone -> warm sunset visual identity.',
      sampleAdCopy: 'Your smartest sessions now come in golden-hour color.',
    },
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    category: 'premium',
    primaryColor: '#0EA5E9',
    secondaryColor: '#0F766E',
    backgroundGradient: ['#02132A', '#02325E', '#0A4C66'],
    accentColor: '#22D3EE',
    successColor: '#34D399',
    errorColor: '#FB7185',
    surfaceColor: '#0A2B45',
    hudStyle: 'glass',
    animationStyle: 'subtle',
    typographyStyle: 'focus',
    soundPack: 'glass_chimes',
    particleEffectType: 'stars',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Deep focus with immersive calm.',
      targetPersona: 'Long-session players wanting low-fatigue visuals.',
      tagline: 'Dive into deep focus.',
      appStoreConcept: 'Underwater gradient with floating particle drift and smooth HUD.',
      instagramStoryIdea: 'Deep work timer reel with ocean ambience and score milestones.',
      beforeAfterConcept: 'Harsh contrast -> smooth ocean depth gradients.',
      sampleAdCopy: 'Stay in flow longer with the Ocean Deep premium skin.',
    },
  },
  {
    id: 'black-gold',
    name: 'Black Gold',
    category: 'premium',
    primaryColor: '#EAB308',
    secondaryColor: '#F59E0B',
    backgroundGradient: ['#050505', '#111111', '#1F1B12'],
    accentColor: '#FDE68A',
    successColor: '#84CC16',
    errorColor: '#FB7185',
    surfaceColor: '#17140D',
    hudStyle: 'glass',
    animationStyle: 'glow',
    typographyStyle: 'elite',
    soundPack: 'elite_orchestra',
    particleEffectType: 'sparkles',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Luxury, power, and authority.',
      targetPersona: 'Premium users who value prestige aesthetics.',
      tagline: 'Luxury in every answer.',
      appStoreConcept: 'Matte black UI with animated gold trim and premium crest icon.',
      instagramStoryIdea: 'Before/after premium reveal with gold foil transition.',
      beforeAfterConcept: 'Basic card UI -> black-gold high-status dashboard.',
      sampleAdCopy: 'Feel premium every session with Black Gold.',
    },
  },
  {
    id: 'diamond-pro',
    name: 'Diamond Pro',
    category: 'premium',
    primaryColor: '#60A5FA',
    secondaryColor: '#A5B4FC',
    backgroundGradient: ['#06122F', '#11224A', '#1E3A8A'],
    accentColor: '#E0F2FE',
    successColor: '#22C55E',
    errorColor: '#FB7185',
    surfaceColor: '#152848',
    hudStyle: 'glass',
    animationStyle: 'glow',
    typographyStyle: 'tech',
    soundPack: 'elite_orchestra',
    particleEffectType: 'sparkles',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Crisp, elite, and precise.',
      targetPersona: 'High-frequency users optimizing personal best records.',
      tagline: 'Precision, cut like diamond.',
      appStoreConcept: 'Crystal UI highlights and faceted panels around equation cards.',
      instagramStoryIdea: 'Diamond shard transition with PB celebration overlay.',
      beforeAfterConcept: 'Soft interface -> sharp faceted premium visuals.',
      sampleAdCopy: 'Upgrade to Diamond Pro and play in crystal precision.',
    },
  },
  {
    id: 'space-launch',
    name: 'Space Launch',
    category: 'premium',
    primaryColor: '#38BDF8',
    secondaryColor: '#F97316',
    backgroundGradient: ['#020617', '#1E293B', '#334155'],
    accentColor: '#FACC15',
    successColor: '#22C55E',
    errorColor: '#F43F5E',
    surfaceColor: '#1B2538',
    hudStyle: 'neon',
    animationStyle: 'energetic',
    typographyStyle: 'tech',
    soundPack: 'neon_pulses',
    particleEffectType: 'stars',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Mission-driven and ambitious.',
      targetPersona: 'Goal-oriented achievers who track streaks and milestones.',
      tagline: 'Launch your brain power.',
      appStoreConcept: 'Rocket-launch countdown visuals tied to combo streaks.',
      instagramStoryIdea: '3-2-1 launch effect when starting sprint mode.',
      beforeAfterConcept: 'Static start button -> launch control sequence animation.',
      sampleAdCopy: 'Every run starts like a mission. Space Launch is for builders.',
    },
  },
  {
    id: 'dark-crimson',
    name: 'Dark Crimson',
    category: 'premium',
    primaryColor: '#DC2626',
    secondaryColor: '#7F1D1D',
    backgroundGradient: ['#0A0205', '#1B0B12', '#3B0E1B'],
    accentColor: '#FB7185',
    successColor: '#22C55E',
    errorColor: '#F43F5E',
    surfaceColor: '#2A1018',
    hudStyle: 'neon',
    animationStyle: 'cyber',
    typographyStyle: 'elite',
    soundPack: 'neon_pulses',
    particleEffectType: 'electric',
    unlockRule: {
      type: 'premium',
    },
    marketing: {
      emotionalFeel: 'Intensity, grit, and high stakes.',
      targetPersona: 'Hardcore players in survival and high-pressure modes.',
      tagline: 'Play under pressure.',
      appStoreConcept: 'Crimson danger UI with heartbeat-style combo pulse effect.',
      instagramStoryIdea: 'Survival mode montage with dramatic red glitch transitions.',
      beforeAfterConcept: 'Relaxed visuals -> high-stakes crimson arena.',
      sampleAdCopy: 'When the pressure is real, Dark Crimson matches your pace.',
    },
  },
  {
    id: 'lab-mode',
    name: 'Lab Mode',
    category: 'limited',
    primaryColor: '#06B6D4',
    secondaryColor: '#2563EB',
    backgroundGradient: ['#F0F9FF', '#E0F2FE', '#DBEAFE'],
    accentColor: '#0EA5E9',
    successColor: '#22C55E',
    errorColor: '#EF4444',
    surfaceColor: '#FFFFFF',
    hudStyle: 'minimal',
    animationStyle: 'subtle',
    typographyStyle: 'tech',
    soundPack: 'matrix_ticks',
    particleEffectType: 'grid',
    unlockRule: {
      type: 'streak',
      minDays: 7,
    },
    marketing: {
      emotionalFeel: 'Scientific and methodical.',
      targetPersona: 'Habit builders who train daily and value progress data.',
      tagline: 'Built by streak. Backed by data.',
      appStoreConcept: 'Clean laboratory HUD with precision meters and experiment badges.',
      instagramStoryIdea: '7-day streak unlock animation with blueprint overlays.',
      beforeAfterConcept: 'Generic screen -> precision lab dashboard.',
      sampleAdCopy: 'Hit a 7-day streak and unlock your personal brain lab.',
    },
  },
  {
    id: 'festival-limited',
    name: 'Festival Limited',
    category: 'seasonal',
    primaryColor: '#F97316',
    secondaryColor: '#EC4899',
    backgroundGradient: ['#3B0764', '#7E22CE', '#F97316'],
    accentColor: '#FDE047',
    successColor: '#22C55E',
    errorColor: '#EF4444',
    surfaceColor: '#5B1E7A',
    hudStyle: 'glass',
    animationStyle: 'energetic',
    typographyStyle: 'retro',
    soundPack: 'retro_bleeps',
    particleEffectType: 'confetti',
    unlockRule: {
      type: 'limited_time',
      campaignId: 'festival_drop_2026',
      startsAtUtc: '2026-03-01T00:00:00.000Z',
      endsAtUtc: '2026-04-15T23:59:59.000Z',
    },
    marketing: {
      emotionalFeel: 'Celebratory and social.',
      targetPersona: 'Event-driven players who want novelty drops.',
      tagline: 'Limited drop. Unlimited vibes.',
      appStoreConcept: 'Festival badge, confetti impacts, and animated event ribbon.',
      instagramStoryIdea: '48-hour countdown sticker for a limited-time skin drop.',
      beforeAfterConcept: 'Standard home screen -> festival event celebration skin.',
      sampleAdCopy: 'Festival Limited is live for a short window. Claim it now.',
    },
  },
] as const;

const THEME_MAP = new Map<string, GameThemeDefinition>(
  THEME_CATALOG.map((theme) => [theme.id, theme]),
);

export function getThemeById(themeId: string): GameThemeDefinition | undefined {
  return THEME_MAP.get(themeId);
}
